### ISSUE TITLE
Purposes page link is broken

### ISSUE THREAD

**Issue by jeswr** [w3c/dpv#159]
In https://w3c.github.io/dpv/dpv/#vocab-purposes the link to the "purposes page" is broken.

It appears that it should be https://w3c.github.io/dpv/dpv/modules/purposes instead of https://w3c.github.io/dpv/modules/purposes.

**Comment by jeswr** [comment]
I've just tried to use the link on that page again, it still appears to be broken.

**Comment by TallTed** [comment]
Confirmed. I think that all links in [the source](https://github.com/w3c/dpv/blob/master/dpv/index.html) that now target —
```html
<a href="/dpv/modules/purposes.html">
```
— or similar should change to —
```html
<a href="./modules/purposes.html">
```
— i.e., all `href="/dpv/` should change to `href="./`

**Comment by coolharsh55** [comment]
Hi. Thanks - and apologies for the issue. The bug is in using this code which should use relative links as Ted points out instead of absolute links - I'll post this fix along with others.

https://github.com/w3c/dpv/blob/96b668ab2311e0a7eef7e349543539f863782dd1/code/jinja2_resources/macro_dpv_document_family.jinja2#L29

**Comment by TallTed** [comment]
https://github.com/w3c/dpv/commit/bbefe477696aad0770fb9b31e618f518007bc292 has "695 changed files with 220,666 additions and 188,803 deletions". This is beyond impossible to review. *AT MINIMUM*, each bullet point should have been its own commit, and really each bullet should have gone through as a PR, such that other eyes could have reviewed it (or at least, tried to do so) before it was merged.

**Comment by coolharsh55** [comment]
Hi Ted, I appreciate nudging us towards best practices, but I don't think what you're asking is feasible. 

1. Each bullet should be a single commit - no, I disagree with this. I don't see any benefit in making additional commits for each typos or fix. I actually prefer bundling such fixes together as its easier to cherry-pick/rebase the fixes to another branch or repo.
2. Number of files: you're not supposed to review all the files - just the source (CSV) or specific outputs (TTL, HTML). Most of these are auto-generated artefacts. If you want to do this, I can provide an example workflow.
3. Using PRs for each commit - no one has volunteered to help with reviewing PRs, so its all just extra work for me to do without any apparent benefit if I have to open the PR and I have to accept my own PR.

**Comment by TallTed** [comment]
@coolharsh55 —

> 1. Each bullet should be a single commit - no, I disagree with this. I don't see any benefit in making additional commits for each typos or fix. I actually prefer bundling such fixes together as its easier to cherry-pick/rebase the fixes to another branch or repo.

"695 changed files with 220,666 additions and 188,803 deletions" suggests strongly that each bullet changes many files with many additions and many deletions, even if some of them are making a single "change all" over those documents. Making each a distinct commit makes it far easier to back one out, if/when necessary. Making each a distinct PR makes it far easier for other eyes to review and suggest changes *before* merge, making if far less likely it will ever be necessary to back one out.

> 2. Number of files: you're not supposed to review all the files - just the source (CSV) or specific outputs (TTL, HTML). Most of these are auto-generated artefacts. If you want to do this, I can provide an example workflow.

NOTHING indicates where/what is the actually changed document/data.

As noted elsewhere, humans don't find CSV at all easy (or often, even possible) to review. I'm pretty confident that the data isn't actually being managed within CSV. If it is, moving it to almost any data management tool that exports to CSV will improve that workflow and make it far easier for humans to review.

> 3. Using PRs for each commit - no one has volunteered to help with reviewing PRs, so its all just extra work for me to do without any apparent benefit if I have to open the PR and I have to accept my own PR.

You might have noticed me making comments. They reflect me trying to review things. Many of my comments say things like, "I find this change(set) difficult/impossible to review, so that's all I can say about this change(set). I hope it didn't make any bad changes."

If/when I find issues with such merged commits, all I can do is complain on the thread where I saw the commit, or open a PR of my own that tries to fix the issue in whatever document I found it ... because it is not easy to know where the "source" data nor the "processor" code lives, in order to make a PR *there*.

If you're going to continue to merge commits directly to `main`, I'll urge you to make notes *in the commit message* of where changes were manually made (i.e., the "source" data or the "processor" code document(s)), and thus where reviewers should focus their efforts.

**Comment by coolharsh55** [comment]
The whole process works like this: data is in Google Sheet spreadsheets which is what is used for discussions and finalising things. Then CSVs are downloaded and stored in `code/vocab_csv` in this repo. Then RDF is generated from them in various formats/serialisations. Then the HTML is generated from the RDF by using templates in `code/jinja_resources`. For primer, guide, etc. there is no RDF, just the HTML template.

So when you want to review: if you want to review just the changed concepts/stuff - the git diff over the RDF or HTML files works e.g. https://github.com/w3c/dpv/commit/bbefe477696aad0770fb9b31e618f518007bc292#diff-d31778b600139a4bfc450f6466d4bc688445d81ef52f07eb4f040acf5ff97ddb for dpv.ttl https://github.com/w3c/dpv/commit/bbefe477696aad0770fb9b31e618f518007bc292#diff-6d14d71a813ef43d2195add0ef7e4eda7dde55ba5f1764a11f450c86a1e9a16d for index.html shows what has changed 

If you want to see what has changed in discussions, or don't want to review the RDF or HTML because you are not a technical person, the source CSVs show the changes - e.g. DPV TOMs module https://github.com/w3c/dpv/commit/bbefe477696aad0770fb9b31e618f518007bc292#diff-48e053c2ee26e782ab73abf8db900521ddcb2a7ca47f4cf8fa443deb9da839be shows what has changed, and now with output format CSV there is another way to see the change e.g. dpv.csv https://github.com/w3c/dpv/commit/bbefe477696aad0770fb9b31e618f518007bc292#diff-06bd2d111c22238fd4e9e88a48d2a83c37f2f54b166d9e7c00252fbf5260e406

The commit message is clear from my perspective on what the changes are. E.g. - "eu-dga: A2-6-Permission parent changed from dpv:NonPersonalDataLegalBasis to dpv:LegalBasis" tells what the change is to the EU DGA extension. The change is present in all files containing the concepts - CSV, RDF, and HTML.

If you want to help - which I think you want to - then I suggest helping us deliver things and creating a "How to Review" guide and focusing on things that improve the documentation of DPV. Things such as individual commits for each minor change are good in theory - but they introduce additional workloads which does not help our case where its just 1 person (me) doing a lot of dev and maintainence work here. Maybe if we had more volunteers - we can improve it over time. But as of now my first priority is to get stuff finished and delivered.
