### ISSUE TITLE
[Review] AI Technology Concepts

### ISSUE THREAD

**Issue by DelaramGlp** [w3c/dpv#162]
1. The AI vocabulary and its documentation <strike>is</strike> **are** available on [GitHub](https://github.com/w3c/dpv).

2.  **ai:System** I think it would be better to rename ``ai:System`` to ``ai:AISystem`` to avoid any confusions.
3.  **ai:System** The link to source (OECD) is not correct. Also it needs to be added to references.

4. **ai:Measure**  I am not sure if ``dpv:TechnicalOrganisationalMeasure`` is broader than ``dpv:Measure''.

**Comment by coolharsh55** [comment]
>     2. **ai:System** I think it would be better to rename `ai:System` to `ai:AISystem` to avoid any confusions.

Okay. Does this mean we would have to prefix AI to everything e.g. AIModel?

> 
>     3. **ai:System** The link to source (OECD) is not correct. Also it needs to be added to references.

Done as https://oecd.ai/en/wonk/ai-system-definition-update

> 
>     4. **ai:Measure**  I am not sure if `dpv:TechnicalOrganisationalMeasure` is broader than ``dpv:Measure''.

Presuming you mean 'ai:Measure' instead of 'dpv:Measure'. If ai:Measure is associated with risk mitigation, then it is a technical and/or organisational measure? So you can reuse the existing taxonomy in DPV e.g. training, policies, and so on.

**Comment by coolharsh55** [comment]
Implemented - please review at https://dev.dpvcg.org/ai/

**Comment by TallTed** [comment]
> [@coolharsh55] Implemented - please review at https://dev.dpvcg.org/ai/

https://dev.dpvcg.org/ai/ is a 404. There must be a better place to point, optimally narrowed to the (cells? lines? paragraphs?) that reflect the specific changes prompted by this issue rather than an entire (directory? document? other?).

**Comment by coolharsh55** [comment]
The link changed because we moved to versioned IRI structure since the last week. Its now https://dev.dpvcg.org/v2.0/ai/ If you open the page, you should be able to find the concepts mentioned and the changes. Asking for exact lines etc. - you can view the git diff if you want, otherwise I think its quite easy to go to the document and see the concepts being discussed here.
