### ISSUE TITLE
Interoperability with other types of consent

### ISSUE THREAD

**Issue by mayaborges** [w3c/dpv#29]
While the focus of this vocabulary is Data the concept of consent is equally applicable to actions. And the consent for an action may be closely tied to consent for the use/transfer of data related to that action. 

For instance consent for your child to go on a field trip is not a fundamentally different than consent for pictures of your child from that field trip to be shared with the rest of the class. The concept of consent is the same in both cases. And it would be advantageous to ask for/store/show the two consents together, perhaps even as two parts/purposes of the same consent. 

Similarly, consent for treatment in a hospital is related to consent for data about said treatment to be shared with other parties such as a primary care physician.  It will be less burdensome for both patient and staff to handle both in the same process flow. Also the consents for treatment without consent for data sharing should not be handled different than consents for treatment with consent for data sharing.

The current description of consent as "Consent of the Data Subject for specified processing" makes that difficult, as consent for actions such as field trips or medical treatment hardly can be described as 'specified processing' and the subject of the consent may or may no be a data subject as well. 

Therefore I suggest broadening the description of consent, for instance to "formal permission for a specified action", which would include 'specified processing'. I do not include '(Data) Subject' because sometimes, e.g. the case of minors, the person(s) giving the consent is not the (data) subject themselves.

**Comment by coolharsh55** [comment]
I understand your perspective. However the DPV is stictly scoped to being about data (privacy / data protection). By stating consent as a broader concept, this opens up complications for also similar broader interpretations and implications of other concepts. For example Legal Basis can be any basis from any law, which is not suitable for the concepts DPV has (e.g. legitimate interest and contract). 

I have no issues with using your definition, just that the scope of 'consent' would still be for data within DPV because consent and its related concepts are defined based on the assumption of 'informed and valid' consent as under data protection / privacy laws and no other source regulating consent. If consent is broadened beyond this, it needs a similar re-interpretation of all related properties pertaining to 'informed' and 'valid' conditions.

For minors, the consent is still about/of the data subject (the minor), but expressed by delegation (e.g. parent/guardian). In this perspective, the 'data subject' is the target of that consent, but not necessarily its initiator or expressing party. This is the view I think GDPR takes as well (Art.8). So you can model this as one instance of consent (the minor) with delegation of expression (e.g. parent) or two instances of consent as one for minor and one for capturing expression of delegation by parent.

**Comment by coolharsh55** [comment]
If there are no updates to this issue by April-30, I will close it in as being out of scope for the group.
