### ISSUE TITLE
Content negotiation / Missing triples

### ISSUE THREAD

**Issue by besteves4** [w3c/dpv#32]
**Content negotiation**
Attempting to dereference [https://w3id.org/dpv#](https://w3id.org/dpv#) (using Postman, or CURL) and explicitly setting the HTTP Accept: header to be text/turtle returns HTML, and not Turtle.
But dereferencing [http://www.w3.org/ns/dpv#](http://www.w3.org/ns/dpv#) does indeed return Turtle for DPV.

**Triples describing DPV as an ontology are missing**
The returned turtle file [here](https://github.com/w3c/dpv/blob/master/dpv/dpv.ttl) only has triples describing DPV-GDPR and not DPV:

```
<https://w3id.org/dpv/dpv-gdpr> a owl:Ontology ;
    dct:abstract "The GDPR extension to Data Privacy Vocabulary provides terms (classes and properties) related to EU General Data Protection Regulation."@en ;
    dct:contributor ...
```

**Comment by coolharsh55** [comment]
Hi. Thanks for noticing. This is my fault - I must not have configured the Apache config in w3id correctly: https://github.com/perma-id/w3id.org/blob/master/dpv/.htaccess Not sure how to fix this. Do you have any suggestions? My guess is to follow this format and see if it works: https://github.com/perma-id/w3id.org/blob/bca40501e47d3a71735d93bb8469d40026c12c08/library/.htaccess

Re. incorrect ontology information where DPV-GDPR is declared instead of DPV, again my fault. I used the wrong metadata input to DPV generation here: https://github.com/w3c/dpv/blob/cf4bad28e4179bf50c377b39e2c2be31dca7d704/documentation-generator/002_parse_csv_to_rdf.py#L448 I'll fix that now.

**Comment by besteves4** [comment]
Hi, I usually follow the format [here](https://github.com/perma-id/w3id.org/blob/bca40501e47d3a71735d93bb8469d40026c12c08/library/.htaccess) yes, so it should work.

**Comment by coolharsh55** [comment]
@besteves4 could you please check whether this (perma-id/w3id.org#2601) works? I've checked with curl for dpv, dpv-gdpr, dpv-skos, dpv-skos/dpv-gdpr, and I get back turtle.

**Comment by besteves4** [comment]
I checked a couple of them and they seem to work well. Thanks!

**Comment by coolharsh55** [comment]
Okay, thank you. I'll close the issue. If you (or anyone) finds anything isn't working as expected, please re-open this issue.
