### ISSUE TITLE
Suitability of `dpv:ThirdCountry` for non-EU uses

### ISSUE THREAD

**Issue by aucampia** [w3c/dpv#60]
Currently DPV has `dpv:ThirdCountry` for "a country outside applicable or compatible jurisdiction as outlined in law".

https://github.com/w3c/dpv/blob/fca0f751fdc7c847df0aa4c355c1aa1172627fd4/documentation-generator/vocab_csv/Jurisdiction.csv#L8

This concept however comes from GDPR, and really does not make a lot of sense if someone is not aware of GDPR regulations specific to the European Economic Area (EEA) and European Union (EU). Would it not be better to use a less EU/EEA/GDPR specific concept in the core vocabulary?

I can't say that I have better ideas than "ThirdCountry" though and I understand that this is somewhat of a propper noun in this case, but still may be worth considering it.

**Comment by coolharsh55** [comment]
Hi. We did discuss the suitability of this term for general usage, but couldn't find any alternatives. So the defintion of the term was modified to ensure it doesn't specifically mention EU. However, AFAIK, "Third Country" is used in other countries outside EU to refer to categories of immigrants (e.g. USA). So without an alternative, its the closest thing we have to express the concept. A lot of terms are very noticeably EU-centric, because of the origin of this work within EU funded projects, but the intended usage is designed and hoped to be compatible with other use-cases.

Also note that `vocab_csv` is the raw data from discussions used to create  DPV documentation, and isn't suggested to be used directly (except for informative purposes). The canonical IRI to use to refer to concepts is https://w3id.org/dpv#ThirdCountry.

**Comment by aucampia** [comment]
Okay fair enough and thanks for the detailed response, I should probably have asked on the mailing list rather.

**Comment by coolharsh55** [comment]
Its fine, the discussion happened :) If you want to leave this open in case there's more stuff to go over now or later - let me know. Otherwise it'll get marked as 'done' at some point.
