### ISSUE TITLE
DPV-defined concepts (e.g. dpv:Concept) have missing `rdfs:isDefinedBy`

### ISSUE THREAD

**Issue by pmcb55** [w3c/dpv#81]
Hi,

I'm writing some basic Best Practice-checking code, and in the process I noticed that there are just 6 terms (from the 631 terms in DPV) that are missing `rdfs:isDefinedBy` triples, namely:
- `dpv:Concept`
- `dpv:isSubTypeOf`
- `dpv:isInstanceOf`
- `dpv:Relation`
- `dpv:hasRange`

I guess this is just an oversight, so is it worth checked and rectifying...?

**Comment by coolharsh55** [comment]
Hi. Not an oversight, but an intentional decision because we hadn't agreed on a formal definition for these terms and their use to create SKOS and OWL termms. 

With the OWL related issues resolved, these concepts will also get their own definitions and metadata in the coming commits. Right now they just have a label.

**Comment by pmcb55** [comment]
Ah! Ok, good to know Harsh - I'll just close this issue now so (since you were already fully aware of this).
Cheers.

**Comment by coolharsh55** [comment]
Hi. Thanks anyways Pat. I've re-opened it, so that the appropriate commit will close this automatically. Just in case implementing it gets delayed for some reason.
